// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvLzX5BRFJKwjvutMOkRGgCWcEr8IlYU',
    appId: '1:273106876436:android:0c7a6389a23b54903e4f01',
    messagingSenderId: '273106876436',
    projectId: 'medisync-e1806',
    storageBucket: 'medisync-e1806.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6OX2KYmkWrfIQs6XQHBVpP3V29BGUMI',
    appId: '1:273106876436:ios:f7734142a500a5cc3e4f01',
    messagingSenderId: '273106876436',
    projectId: 'medisync-e1806',
    storageBucket: 'medisync-e1806.firebasestorage.app',
    iosBundleId: 'com.example.medisync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALnXE0SsSK0pI0misnjJvMhitKv66TNZY',
    appId: '1:273106876436:web:342fe180c68564c83e4f01',
    messagingSenderId: '273106876436',
    projectId: 'medisync-e1806',
    authDomain: 'medisync-e1806.firebaseapp.com',
    storageBucket: 'medisync-e1806.firebasestorage.app',
    measurementId: 'G-TY675FS1WE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALnXE0SsSK0pI0misnjJvMhitKv66TNZY',
    appId: '1:273106876436:web:342fe180c68564c83e4f01',
    messagingSenderId: '273106876436',
    projectId: 'medisync-e1806',
    authDomain: 'medisync-e1806.firebaseapp.com',
    storageBucket: 'medisync-e1806.firebasestorage.app',
    measurementId: 'G-TY675FS1WE',
  );
}
